import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Header from '../templates/Header';
import Footer from '../templates/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Matheus App',
    description: 'Generated by Matheus Macedo'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body
                className={inter.className + ' flex flex-1 flex-col h-screen'}
            >
                <Header />
                <main className="flex flex-1">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
